### ISSUE TITLE
Begged mouse with gamescope enabled

### ISSUE THREAD

**Issue by StellarHarbour** [ValveSoftware/gamescope#1207]
I use gamescope -w 3840 -h 2160 -W 1920 -H 1080 -f -- %command% for downscaling and when I play Hunt: Showdown 
Symptoms include: when I open the map in Hunt: Showdown and then move the mouse while closing it, the mouse position gets messed up, causing the character to look into the sky or floor.

**Comment by sharkautarch** [comment]
> I use the command gamescope -w 3840 -h 2160 -W 1920 -H 1080 -f -- %command% for downsampling when playing Hunt: Showdown. However, I encounter a problem where, upon opening the map and moving the mouse while closing it, the mouse position becomes disoriented, causing the character to look into the sky or floor.
> 
> Previously, this issue was a KDE bug, but it appears to be fixed now. As a workaround, I used --force-grab-cursor, but now gamescope itself seems to have this bug for some reason. So I'm forced to use it to fix the issue again
> 
> Related KDE bug tracker issue: https://bugs.kde.org/show_bug.cgi?id=458233


Fixed in git upstream, but fix isn't in the latest release version yet

if you are on archlinux, use the aur gamescope-git package

See:
- original issue: https://github.com/ValveSoftware/gamescope/issues/1145
- my request for a new release version which would propagate in the fix: https://github.com/ValveSoftware/gamescope/issues/1187

**Comment by sim590** [comment]
I have tried the latest `gamescope-git`, on Archlinux, version `3.14.26.r3.gf35e1b38-1` and I still experience the mouse going a bit crazy when I interchange mouse mode from cursor mode (in the game UI) and character camera mode by pressing TAB in the game DayZ:


https://github.com/user-attachments/assets/5dd65489-d124-4362-b377-21017e2eaad0
