### ISSUE TITLE
Cursor not locking (not respecting --force-grab-cursor)

### ISSUE THREAD

**Issue by HaydenBat** [ValveSoftware/gamescope#1285]
When using `--force-grab-cursor`, the cursor is initially grabbed until another window or workspace is interacted with, then the cursor is not locked when back in gamescope. Without the `--force-grab-cursor` argument, the issue was still present, some games fixing the problem by opening and closing the pause menu, others not.
There is also a window border which was not present beforehand, but probably irrelevant.

- OS: Arch Linux
- Kernel: 6.8.9-zen1-1-zen
- Hyprland latest git
- Using latest git - aur `gamescope-git` package

https://github.com/ValveSoftware/gamescope/assets/65262176/56fe3ed6-1378-43cc-8246-5113a0af8178

**Comment by cptn-cosmo** [comment]
I have the same issue still, Final Fantasy XIV basically became unplayable for me since I can't reliable move with mouse only and i keep getting turned around and running the wrong way.

**Comment by HaydenBat** [comment]
I found similar issues here https://github.com/ValveSoftware/gamescope/issues/1181 and here https://github.com/hyprwm/Hyprland/issues/5076 , but these were fixed using `--force-grab-cursor` which doesn't work.

**Comment by Joshua-Ashton** [comment]
I don't think this is our bug, it works on every other compositor I tested just fine.

**Comment by cptn-cosmo** [comment]
I am using [niri](https://github.com/YaLTeR/niri) and it worked fine until the last package update (3.14.3). i have since switched to the -git version and it is still broken for me

**Comment by cptn-cosmo** [comment]
https://github.com/ValveSoftware/gamescope/assets/7382310/0671b1d3-ed35-4da1-93de-a210ce3ba357

Here is an example i recorded, at first just left clicking and the camera moving without input, which happens twice at the start of the video, then i walked around a bit and it happened with both left & right click simultaneously as well at the end of the video. This was working fine in a previous release of gamescope with the same compositor, unfortunately I did not take note of the version that was last working.

**Comment by lodriguez** [comment]
Same here on arch linux using plasma6. 3.14.2 works like expected. 3.14.3 (last version on arch). The Cursor bugs for me and isn't caught like before. At 3.14.13 or latest Git force-grab-cursor isn't working at all. (haven't tried anything between 3.14.3 and 3.14.13)

**Comment by bfalk8** [comment]
> I found similar issues here #1181 and here [hyprwm/Hyprland#5076](https://github.com/hyprwm/Hyprland/issues/5076) , but these were fixed using `--force-grab-cursor` which doesn't work.

I can confirm that since that hyprland issue has closed, any gamescope release past 3.14.3 has broken `--force-grab-cursor` for me

**Comment by HaydenBat** [comment]
Turns out my issue was a [Hyprland one](https://github.com/hyprwm/Hyprland/issues/5992). Downgrading to [Hyprland 0.39.1](https://archive.archlinux.org/packages/h/hyprland/hyprland-0.39.1-5-x86_64.pkg.tar.zst.sig) looks to have fixed the issue for me. Sorry for the inconvenience. Looks like others in this issue seem to be having slightly different problems so I'll leave this open for now as theirs still fit the title description, unless anyone wants otherwise.
Thanks for the help.

**Comment by The-Briel-Deal** [comment]
Looking into this currently. More info in https://github.com/hyprwm/Hyprland/issues/6159.

**Comment by lodriguez** [comment]
> Looking into this currently. More info in [hyprwm/Hyprland#6159](https://github.com/hyprwm/Hyprland/issues/6159).

It's not only Hyprland, Plasma6 as well. 3.14.2 is the last working Version.

**Comment by tannertechnology** [comment]
Encountering this under X11 running KDE Plasma 6.1.0, did previously work on Plasma 6. Seems to happen when games allow cursor movement like in menus. For War Thunder this is a problem, it never tries to bind the cursor properly on linux, previously gamescope resolved this.

**Comment by DocMAX** [comment]
why isn't there a simple hotkey like SUPER+G available for forced mouse grab beside
"Super + G                      toggle keyboard grab"
????
I can't understand.
Shall i create a PR?

**Comment by LJ-Software** [comment]
I just had this show up for me after upgrading from `3.16.1` to `3.16.3`.

After downgrading back to `3.16.1` `--force-grab-cursor` works for me.

**Comment by jarrard** [comment]
Can confirm, was having this issue with xcom2, downgraded from .3 to .1 and not it captures cursor correctly.

**Comment by Gigantoad** [comment]
Same.

**Comment by codevski** [comment]
3.16.2 also works. (Arch + hyprland)

**Comment by jarrard** [comment]
Still broken in 3.16.4 as well.

**Comment by jiriks74** [comment]
Since this will be a year old in a *few* days I'd like to chip in as well.

I can confirm that `3.16.4` is broken.
I can confirm that `3.16.2` does work.

Using:

| | |
| ------------------------------------ | -------------------------------------------------------------------: |
| Operating System             | `NixOS 25.05`                                                             |
| KDE Plasma Version          | `6.3.4`                                                                          |
| KDE Frameworks Version | `6.13.0`                                                                        |
| Qt Version                           | `6.9.0`                                                                           |
| Kernel Version                    | `6.14.2 (64-bit)`                                                          |
| Graphics Platform             | `Wayland`                                                                    |
| Processors                          | `8 × Intel® Core™ i5-9300H CPU @ 2.40GHz`       |
| Memory                              | `15,5 GiB of RAM`                                                       |
| Graphics Processor 1        | `Intel® UHD Graphics 630`                                      |
| Graphics Processor 2        | `NVIDIA GeForce GTX 1650 with Max-Q Design` |

**Comment by jarrard** [comment]
Maybe will need to do a debug between these versions ourself to find the exact bit of code that does it, then produce a fix patch ourselves.   I've done it once before years ago, going to need to relearn how to do it as I forgot, pretty basic github stuff but!

**Comment by matte-schwartz** [comment]
The most recent issue in 3.16.4 has been bisected to https://github.com/ValveSoftware/gamescope/issues/1806#issuecomment-2791215115

**Comment by jarrard** [comment]
Neat, yeah bisect is what I was searching for. 

Hope a fix can be found then.

**Comment by kekonn** [comment]
Can confirm this on CachyOS with version 3.16.4

**Comment by morti86** [comment]
Can confirm on Arch with Snowbreak. The --force-grab-cursor doesn't help. KDE Plasma + Wayland

**Comment by OriginalAlienOne** [comment]
Can confirm on Bazzite version 42. The --force-grab-cursor doesn't help on this OS either. KDE Plasma + Wayland

**Comment by Mondrethos** [comment]
Can confirm on Bazzite/Arch/EndeavourOS, downgrading to 3.16.2-1 fixes the issue.

**Comment by matte-schwartz** [comment]
the fix for this landed in the latest release

**Comment by Mondrethos** [comment]
Anyone have a chance to test this?

**Comment by jarrard** [comment]
Well I've been using 3.16.9 and it seems to be working again.

**Comment by morti86** [comment]
On Arch it works fine now with Snowbreak.

**Comment by razhterize** [comment]
I'm not quite sure how it happen, but `--force-grab-cursor` works fine for me
that is, until mangohud statistic is shown with `--mangoapp` flag.
whenever magohud is showing, cursor easily escape gamescope window, but when it's hidden/not shown, cursor locks back to the gamescope window

- `EndeavourOS x86_64`
- Gamescope `3.16.9+` (installed from `pacman`)

**Comment by lynxbites** [comment]
Fedora 42
Downgrading from gamescope `3.16.4-2.fc42` to `3.16.2-1.fc42` fixed the issue for me.
`sudo dnf install gamescope-0:3.16.2`

**Comment by DSDV** [comment]
can confirm @razhterize 
`[gamescope] [Info]  console: gamescope version 3.16.11+ (gcc 15.1.1)`
on latest nobara. 
the mouse capture breaks when the mangohud `--mangoapp` argument is used :/

**Comment by kisak-valve** [comment]
Closing as fixed.

Looks like the --mangoapp variant is being tracked at #1466.

**Comment by DarkPhilosophy** [comment]
It was waylan, as soon as I activated experimental wayland it mouse stay in the window

**Comment by SliceJosiah** [comment]
How is this fixed? I'm having this problem.
