### ISSUE TITLE
Gamescope launches on wrong monitor

### ISSUE THREAD

**Issue by klazoklazo** [ValveSoftware/gamescope#1345]
I play on a laptop connected to an external monitor, I'm using Fedora 40 KDE, and games running through gamescope will always launch on my laptop's monitor instead.

I would like for there to be a way to specify which kind of monitor gamescope can launch on, so that this doesn't end up being a problem.

**Comment by matte-schwartz** [comment]
Does specifying a display with `--display-index` not work? Was working for me fine earlier on Fedora 40.

**Comment by klazoklazo** [comment]
OH, I didn't see that in the list after inputting `--help`, thanks. Although I'm now running into a separate issue, where my aiming is very, very off? Right now I'm trying this in Earth Defense Force 5, but the game fails to lock my cursor to the middle of the screen.

**Comment by klazoklazo** [comment]
OKAY, so I used `--force-cursor-grab` to try and fix it, but now Steam integration is failing, and `-e` isn't forcing it back on.

**Comment by Joshua-Ashton** [comment]
-e always works, your issue must be something else.

**Comment by klazoklazo** [comment]
`gamemoderun gamescope -h 1080 -S integer -e -f --force-cursor-grab --display-index 1 -- %command%`

**Comment by DonKatsu** [comment]
Opening on the wrong monitor with Plasma 6 should be this? #1224
But as I wrote there, gamescope 3.14.3 did something that worked around the Plasma 6 issue for me. Is Fedora 40 still using gamescope 3.14.2?

**Comment by klazoklazo** [comment]
Fedora 40 is still using gamescope 3.14.2 yes, the Flatpak hosting gamescope for me is also stuck on 3.14.2. I'm not exactly sure of a way to upgrade if this fixes an issue then?

**Comment by klazoklazo** [comment]
Okay so after doing a bunch of much-needed research:
- The issue at hand wasn't actually gamescope displaying on an incorrect monitor, that additional argument `--display-index` mentioned fixed that specific issue
- But gamescope also now consistently is broken in terms of Steam integration (the Steam overlay won't show, and notifications aren't displayed), alongside mouse aiming being broken without using `--force-cursor-grab`, at least for the games I've tested (Earth Defense Force 5, Team Fortress 2). Using `-e` does not fix this for me.
- No one's properly released a version past 3.14.2, resulting in me being unable to upgrade to a version that fixes this. Trying to compile the program from scratch has just given me dependency errors while compiling, notably issues where it cannot detect some of my packages(?)

There's posts that have mentioned the aiming issues being fixed in future versions that I cannot access, but I don't think anyone's mentioned the issues on Steam integration yet, so I'm renaming the post to that

**Comment by matte-schwartz** [comment]
>     * But gamescope also now consistently is broken in terms of Steam integration (the Steam overlay won't show, and notifications aren't displayed), alongside mouse aiming being broken without using `--force-cursor-grab`, at least for the games I've tested (Earth Defense Force 5, Team Fortress 2). Using `-e` does not fix this for me.
> 
I am not having any issues using `-e` on latest gamescope master, and cursor behavior has changed massively since version 3.14.2

>     * No one's properly released a version past 3.14.2, resulting in me being unable to upgrade to a version that fixes this. Trying to compile the program from scratch has just given me dependency errors while compiling, notably issues where it cannot detect some of my packages(?)
> 
Since you say you're on Fedora 40, you can try to either install my testing build I've been using for Nobara 40 or you can take the .spec and compile it yourself:
https://copr.fedorainfracloud.org/coprs/matte-schwartz/nobara-40-staging/build/7501377/

**Comment by klazoklazo** [comment]
Oh, I'm not really sure how to do COPR stuff, nor compile from a ".spec" file?

**Comment by MauroGuida** [comment]
> Okay so after doing a bunch of much-needed research:
> 
>     * The issue at hand wasn't actually gamescope displaying on an incorrect monitor, that additional argument `--display-index` mentioned fixed that specific issue
> 
>     * But gamescope also now consistently is broken in terms of Steam integration (the Steam overlay won't show, and notifications aren't displayed), alongside mouse aiming being broken without using `--force-cursor-grab`, at least for the games I've tested (Earth Defense Force 5, Team Fortress 2). Using `-e` does not fix this for me.
> 
>     * No one's properly released a version past 3.14.2, resulting in me being unable to upgrade to a version that fixes this. Trying to compile the program from scratch has just given me dependency errors while compiling, notably issues where it cannot detect some of my packages(?)
> 
> 
> There's posts that have mentioned the aiming issues being fixed in future versions that I cannot access, but I don't think anyone's mentioned the issues on Steam integration yet, so I'm renaming the post to that

On my end, the mouse aiming issue has been fixed in version 3.14.18. I no longer have to use `--force-cursor-grab`. However, the Steam integration is still broken. With or without the `-e` (or `--steam`) flag, the overlay does not show up and Steam input does not work. The only way to make the Steam integration work is to launch gamescope separately in a terminal (the Steam integration flag is not required) and set `DISPLAY=:1 %command%` as the game launch option. `:1` is not arbitrary; it is where Gamescope has started the Xwayland session, as indicated by `wlserver: [xwayland/server.c:107] Starting Xwayland on :1`.

**Comment by MauroGuida** [comment]
> Replying to [#1345 (comment)](https://github.com/ValveSoftware/gamescope/issues/1345#issuecomment-2143685174)

It appears that the issue has been fixed in Gamescope version `3.14.24`. With Gamescope set as a launch parameter Steam integration functions as expected.

**Comment by Virkkunen** [comment]
> > Replying to [#1345 (comment)](https://github.com/ValveSoftware/gamescope/issues/1345#issuecomment-2143685174)
> 
> It appears that the issue has been fixed in Gamescope version `3.14.24`. With Gamescope set as a launch parameter Steam integration functions as expected.

I'm running 3.14.29.r9.g94271f31-1 with the `-e` flag and this issue still happens, no overlay for me.

**Comment by mikeyjoel** [comment]
Running into the same issue. Have to constantly Disable Steam Input and have a headache with AntiMicroX. I'll test on X11 in a bit.

```
OS: openSUSE Tumbleweed x86_64
Kernel: Linux 6.14.6-1-default
DE: KDE Plasma 6.3.5
WM: KWin (Wayland)
gamescope-3.16.1-2.4.x86_64
Vendor : obs://build.opensuse.org/games:tools
```
