### ISSUE TITLE
[NVIDIA] frames stop being presented (and appear to hang) sporadically when using the WSI layer and VK_KHR_present_wait

### ISSUE THREAD

**Issue by matte-schwartz** [ValveSoftware/gamescope#1592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [X] The issue occurs on upstream gamescope without any modifications

### Current Behavior

Some games, especially Sony PlayStation ports, seem to hang and stop presenting frames even while game audio remains in the background. The most consistent repro I have of this now is with God of War: Ragnarok, with the launch option:
`gamescope --hdr-enabled -e -f -h 2160 -w 7680 -r 120 -- %command%`

around 50% of the time, the game will hang at some point within the first 20-30 seconds or so. will include screenshots of what this looks like + in-game settings

### Steps To Reproduce

1. Launch God of War: Ragnarok with `gamescope --hdr-enabled -e -f -h 2160 -w 7680 -r 120 -- %command%`
2. Attempt to load the game
3. If gamescope hangs on one frame, while otherwise remaining responsive, you've hit the issue

If you don't freeze on launch and load-in, try quitting and re-launching 1-2 more times.

### Hardware information

```markdown
- Distro: Arch Linux
- CPU: 13th Gen Intel(R) Core(TM) i9-13900K
- GPU: NVIDIA GeForce RTX 4090
- Driver Version: NVIDIA 565.57.01
```

### Software information

```markdown
- Desktop environment: Plasma 6.2.1
- Session type: Wayland
- Gamescope version: 3.15.13
- Gamescope launch command(s): `gamescope --hdr-enabled -e -f -h 2160 -w 7680 -r 120 -- %command%`
```

### Which gamescope backends have the issue you are reporting?

- [X] Wayland (default for nested gamescope)
- [X] DRM (default for embedded gamescope, i.e. gamescope-session)
- [ ] SDL
- [ ] OpenVR

### Logging, screenshots, or anything else

After gamescope hangs:
![image](https://github.com/user-attachments/assets/1160bf67-1bac-4691-be73-64376e809a78)

in-game settings from a successful launch (no changes from the hang):
![Screenshot_20241022_150829](https://github.com/user-attachments/assets/f51451c9-9e20-46f2-9b08-739079cd3a3d)

bug report immediately after a hang:
[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/17482658/nvidia-bug-report.log.gz)

Proton log from a hang:
[steam-2322010.tar.gz](https://github.com/user-attachments/files/17482661/steam-2322010.tar.gz)

**Comment by matte-schwartz** [comment]
@cubanismo I was still able to repro the WSI hang in God of War: Ragnarok, here's a new issue report as there were no matches I was finding

**Comment by pbasov** [comment]
Can confirm the same issue with Elden Ring on `565.57.01` with launch command:
`gamescope -w 3840 -h 2160 --adaptive-sync  -f  --hdr-enabled --fullscreen -- %command%`

Game launches, HDR works. After 3-5 minutes of gameplay usually hangs with sound running in background.

**Comment by cubanismo** [comment]
Thank you for the reports and log files. I've filed NVDIA internal bug 4924590 to track our investigation of this issue.

One other question so far: Is my memory correct that this issue occurred with prior NVIDIA drivers (560 or 555-series) as well?

**Comment by cubanismo** [comment]
One other question: If you grab a screenshot from within gamescope (Super + S) after the hang, does it show more up-to-date content, or is it in the same as the "stuck" visible image? I'm not clear how the attached screenshots were captured, so just checking to be sure.

**Comment by matte-schwartz** [comment]
@cubanismo yes, as far as I know it has gone back to the 555 series, but I also did not really use nvidia with gamescope much prior to that. I can try to test some older releases to confirm if you'd like.

Those screenshots above were using Spectacle on KDE via the PRTSC button on my keyboard. I just tested using `gamescopectl screenshot ~/Pictures/god-of-war-freeze.png` and that also shows the same stuck visible image, which it captures once I re-focus the gamescope window after alt + tabbing to execute the command. 
![god-of-war-freeze](https://github.com/user-attachments/assets/4243b1a3-415a-4988-bb02-317c58cd3264)

The game was frozen prior to me alt-tabbing fwiw

**Comment by cubanismo** [comment]
Thanks for testing. If it goes back to at least 555-series drivers, that's good enough. No need to check older drivers at the moment. Gamescope support in general gets pretty spotty prior to that.

**Comment by tlneondo** [comment]
I think this may be specifically something with egl-wayland, as gamescope was having this issue, I went and tried to use the wine-wayland driver in Baldur's gate 3 and it looks like I'm getting the exact same kind of freezing shortly after launch.

**Comment by valgusk** [comment]
did you try disabling vk_khr_present_wait? I don't know why or where the bug is originating (either vkd3d or nvidia), but usually it helps with hdr+wayland

**Comment by matte-schwartz** [comment]
not seeing much of a difference with `vk_khr_present_wait` disabled both in compilation and as an env var.

**Comment by adamdmoss** [comment]
I can also repro this pretty easily (usually within seconds or minutes) if it helps.  Not sure if the game matters, but I can repro with Silent Hill 2, Ratchet & Clank, Death Stranding and some random others.
Mostly been trying driver 565.57.01 but saw the same with 560.35.03.  (550.135 was a non-starter in casual testing, some drm failure but I didn't look deeply.)

**Comment by adamdmoss** [comment]
I can alt-tab in and out of gamescope and the same frozen frame is displayed, so technically I think gamescope hasn't hung (maybe the compositor has though, since I don't get a wiggly mouse-cursor).

The game itself continues to take CPU time on some threads, but no longer seems to be responding to input or (of course) visibly outputting new frames.

Maximal logging on gamescope shows nothing unusually suspicious.
PROTON_LOG on the game(+proton) itself shows nothing unusually suspicious.
dmesg shows nothing unusual from the NV drivers etc.

**Comment by adamdmoss** [comment]
vk_khr_present_wait=false is also not helping for me.

**Comment by adamdmoss** [comment]
Well!  `VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_wait` did help, however.  Many hours of stability now.

**Comment by matte-schwartz** [comment]
Disabling the extension via `VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_wait` does seem to be helping here in God of War: Ragnarok so far, will keep testing a few other games just to make sure.

**Comment by jarrard** [comment]
> Disabling the extension via `VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_wait` does seem to be helping here in God of War: Ragnarok so far, will keep testing a few other games just to make sure.

I'm going to test this out with Stalker-2 which appears to have a very similar random instability crash issue when GS and HDR is enabled.

**Comment by jtellm** [comment]
It seems `VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_wait` fixes the freezing issue for me too (Fedora 41, GNOME, gamescope 3.15.13, NVIDIA 565.57.01 driver) although `--force-grab-cursor` was neccesary in some cases to avoid crashing.

I am noticing some strange flickering with HDR enabled but I'm not sure if this is related to gamescope.

**Comment by matte-schwartz** [comment]
> UPDATE: Sadly no go, stalker2 and hdr just silent ctd.  I'll probably need to keep waiting for more people to encounter this bug before a solution is found. Seems almost nobody is using HDR atm.

The issue described here isn't a crash but rather a freeze, so you are likely hitting a different issue.

**Comment by jarrard** [comment]
True I opened up a separate issue for this problem. 

https://github.com/ValveSoftware/gamescope/issues/1633

**Comment by postcert** [comment]
> Well! `VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_wait` did help, however. Many hours of stability now.

This fixed my Stalker 2 issues on gamescope when using `--force-grab-cursor` (fine without it but unplayable input wise)
Had a similar issue with a single rendered frame and gameplay continuing in the "background"

**Comment by tlneondo** [comment]
Can confirm here, disabling VK_KHR_present_wait seems to get me further in game into Armored Core 6 than usual.

**Comment by matte-schwartz** [comment]
> Can confirm here, disabling VK_KHR_present_wait seems to get me further in game into Armored Core 6 than usual. But that's not a solution for DX11 titles.

Do you know of any specific DX11 titles offhand that are broken on NV w/ gamescope in a similar way?

**Comment by adamdmoss** [comment]
> > Can confirm here, disabling VK_KHR_present_wait seems to get me further in game into Armored Core 6 than usual. But that's not a solution for DX11 titles.
> 
> Do you know of any specific DX11 titles offhand that are broken on NV w/ gamescope in a similar way?

IIRC: Alone In The Dark, Blacksad, Uncharted(?).  Probably more.

**Comment by matte-schwartz** [comment]
Thanks, Blacksad: Under The Skin hangs for me under gamescope.

**Comment by jarrard** [comment]
I said this in another thread but Stalker-2 becomes unstable for me with VRR and HDR, you eventually get gamma flutters and nano-stutters.  Doesn't occur under Windows so that is where I'm playing the game atm.

**Comment by matte-schwartz** [comment]
@jarrard please do not cross-post for issues, it makes it much more difficult to keep track of things. this specific thread is about something different.

**Comment by matte-schwartz** [comment]
I found some DirectX 11 games in my library that froze reliably on NVIDIA with HDR (Disco Elysium, Ori and the Will of the Wisps) using gamescope's DRM backend, and was finally able to find a way to work around the freezing in-game without sacrificing HDR in both vkd3d-proton and DXVK, at least locally on my setup.   

Since there is no way to disable Vulkan extensions at runtime like there is with vkd3d-proton, you will have to rebuild DXVK with a patch that essentially just removes the Vulkan capability for present wait if it detects NVIDIA drivers in-use. I was actually able to find workarounds that were used in the past within both repos to do exactly the same thing because of some problematic NVIDIA driver versions, so re-tooling those for debugging this issue was relatively straightforward.

You can use [this combined patch](https://gist.github.com/matte-schwartz/4431745217ec7e24344a4a1f769e0ef7) that I created that is meant to re-compile Proton following the [README.md](https://github.com/ValveSoftware/Proton?tab=readme-ov-file#obtaining-proton-sources) to obtain the latest Proton sources, checkout `bleeding-edge` with `git checkout bleeding-edge`, applying the patch with `patch -p1 < disable-nvidia-vk-khr-present-wait.patch` (or whatever you saved the contents of that gist as), and then proceed to rebuild Proton. The advantage of this is that you can keep an entire Proton version separate from Valve's standard proton versions specifically to use just for problematic games in gamescope.

If you'd prefer to only re-build the individual components of [vkd3d-proton](https://github.com/HansKristian-Work/vkd3d-proton) and [dxvk](https://github.com/doitsujin/dxvk) (much lighter to compile than a whole Proton build) then you can apply [this patch to vkd3d-proton](https://gist.github.com/matte-schwartz/9cfcf5c155aff73d6ba4cf7ad263512d) and [this patch to dxvk](https://gist.github.com/matte-schwartz/feb1c49286f5acdab6c612963d58a796) while following their READMEs.

There's still one freeze without using any games while in the Steam Deck UI of gamescope-session when HDR is already enabled in the session that I'm trying to track down the source on, but would be good to know if anyone ends up trying these two patches and if they help or hurt specifically while in-game.

**Comment by tlneondo** [comment]
Still seeing issues on 565.77. Hope we get some good news when 570 finally drops.

**Comment by danielgormly** [comment]
Yes 565.77 with GTX2060 Mobile on ARCH. I've tried both INSIDE & Dark Souls Remastered and experience the same freezing/non-responsiveness while the audio continues.

INSIDE lasts between seconds to 25min. I can consistently get it freeze few seconds by leaving off immediate mode in hyprland and switch windows quickly. It has no vsync option & I couldn't get any other hack working i.e. `VK_KHR_present_wait`.

Dark Souls Remastered on the other hand, with vsync off, runs with perfect stability.

To launch gamescope in the first place, I have to launch it with the Intel GPU, but then nvidia takes over for the game. It dumps core otherwise, like in [issue 497](https://github.com/ValveSoftware/gamescope/issues/497). That might put me in a special category.

**Comment by matte-schwartz** [comment]
>In reply to: https://github.com/ValveSoftware/gamescope/issues/1592#issuecomment-2545415775

INSIDE looks like D3D11 which means that using `VKD3D_DISABLE_EXTENSIONS` has no effect, you'd have to rebuild DXVK as outlined here: https://github.com/ValveSoftware/gamescope/issues/1592#issuecomment-2525409950. Or is it still freezing even with DXVK that has `VK_KHR_present_wait` patched out for NVIDIA?

**Comment by brain-anti-freeze** [comment]
Thanks @matte-schwartz for logging this ! I've been having this issue for a very long time.  Like @adamdmoss I'm using the DRM backend (to a Samsung TV over HDMI) and I get this issue when I enable _either_ HDR, the WSI layer, or both - with HDR and WSI both disabled it works OK.

It also sounds like it might be more repeatable in my setup than you are seeing - I always get the freeze in any dx11 or dx12 game using proton in the first 30-90 seconds.  I'm using the gamescope-session setup where steam is run separately from gamescope with the `DISPLAY` and `GAMESCOPE_WAYLAND_DISPLAY` environment variables set.    I'm pretty sure I also used to be able to easily recreate this by running `gamescope --hdr-enabled vkcube` in a tty, but I tried that again now and it seems to work OK.

Curious if @cubanismo has been able to root-cause this any further ?  I noticed  this comment in the layer https://github.com/ValveSoftware/gamescope/blob/1c9495c359e88a95e4f681a6d3f72974bbe1f236/layer/VkLayer_FROG_gamescope_wsi.cpp#L1141 about forcing `VK_PRESENT_MODE_MAILBOX_KHR`  to the driver, but the output of `vulkaninfo` shows that the nvidia driver doesn't support it 
```
Present Modes: count = 2
                PRESENT_MODE_FIFO_KHR
                PRESENT_MODE_IMMEDIATE_KHR
```
(I also saw [this post](https://community.khronos.org/t/vulkan-doesnt-detect-all-compatible-present-modes/110134) that suggests that sending that mode to the nvidia regardless doesn't cause an error but perhaps doesn't perform correctly).  I was wondering if something was going on like the driver was stalled waiting for commits it submitted but which have been dropped so will never be presented, or just some other incompatibility with using an unsupported mode ... 

I've found this to be a successful workaround - #1671 - so far no hangs and HDR looks great (on 565.77, it was washed out in earlier versions).

**Comment by tlneondo** [comment]
Still seeing this issue on the new Nvidia 570 drivers. Gamescope patch is working, but Wine-Wayland will lock up. It'll do so even in an old game like Thief 1 with the NewDark engine, where going from the menu to rendering 3D I believe creates a new display mode internally.

**Comment by sequethin** [comment]
so, manually applying this patch on a custom build of gamescope and then using that env var is still the only way around this freeze, is that right?

**Comment by matte-schwartz** [comment]
Yes, unless https://github.com/ValveSoftware/gamescope/issues/1671 gets merged or there is a driver fix that fixes the root cause of the issue.

**Comment by pbasov** [comment]
Elden Ring with HDR is seemingly fixed with 570.124 nvidia drivers

**Comment by adamdmoss** [comment]
> Elden Ring with HDR is seemingly fixed with 570.124 nvidia drivers

Alas still hangs after a while with 570.124 here on a variety of titles as usual.

**Comment by Syntist** [comment]
https://developer.nvidia.com/vulkan-driver

Please try Linux 570.123.06, I think it fixes the issue
WineWayland with Vsync working fine now.

**Comment by matte-schwartz** [comment]
yes, seems like 570.123.06 resolves the issue on my end as well

**Comment by brain-anti-freeze** [comment]
Vulkan dev driver 570.123.06 resolves the issue for me too, hopefully the fix makes it into a mainstream driver soon

**Comment by matte-schwartz** [comment]
575.51.02 driver notes mention:

`Fixed a bug that could cause the applications that use the VK_KHR_present_wait extension to hang on Wayland.`

So this issue should be resolved now.

**Comment by sequethin** [comment]
what a happy day it would be indeed if I could abandon my private fork of gamescope and still play my games with HDR 👍🏼 thanks for the note @matte-schwartz

**Comment by matte-schwartz** [comment]
can confirm the issue is resolved on 575 after testing it for the day
