### ISSUE TITLE
Cursor/Mouse Region options in Steam Input stay invisible after initial 3000ms timeout, Mouse/Joystick Mouse work as expected

### ISSUE THREAD

**Issue by matte-schwartz** [ValveSoftware/gamescope#1602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [X] The issue occurs on upstream gamescope without any modifications

### Current Behavior

Bisected to: https://github.com/ValveSoftware/gamescope/commit/d7758a8d7eae69384a33263eee267d60fdcc98f9
Original report: https://github.com/ValveSoftware/SteamOS/issues/1681

I investigated Grim Dawn (219990), and it regresses between 3.13.19 and 3.14.1 in the `jupiter-main` repo which I then bisected between on my OLED Deck.

After the bisected bad commit, the mouse in the menu of Grim Dawn goes from always showing when using the default layout and moving the mouse with the right touchpad to rarely showing under the same conditions. it **does** show properly until the 3000ms timeout if you touch the screen directly or if you invoke the cursor by holding the Steam button and using the touchpad.__

EDIT: the bad behavior continues on desktop when using both `gamescope -f -- %command%` and `gamescope -f --force-grab-cursor -- %command%` on SteamOS 3.6.19

### Steps To Reproduce

1. Launch Grim Dawn
2. Once in the main menu, attempt to use the right touchpad to move the cursor
_The mouse will remain invisible while still interacting with the menu_
3. Hold the Steam button and move the mouse
_The mouse will appear, but only for 3000ms as set in gamescope-session_

### Hardware information

```markdown
- Distro: SteamOS 3.6.19
- CPU: AMD Custom APU 0932
- GPU: Advanced Micro Devices, Inc. [AMD/ATI] Sephiroth [AMD Custom GPU 0405] [1002:1435] (rev ae)
- Driver Version: Mesa 24.1
```

### Software information

```markdown
- Desktop environment: N/A
- Session type: gamescope-session
- Gamescope version: 3.15.13
- Gamescope launch command(s): N/A
```

### Which gamescope backends have the issue you are reporting?

- [ ] Wayland (default for nested gamescope)
- [X] DRM (default for embedded gamescope, i.e. gamescope-session)
- [X] SDL
- [ ] OpenVR

### Logging, screenshots, or anything else

<details><summary>running gamescope with wlserver debug logging shows a ton of the same sequence of events whenever the cursor is moved</summary>

```
Oct 28 22:56:48 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef9965990)
Oct 28 22:56:48 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:48 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:48 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef992b460)
Oct 28 22:56:48 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef99a5d60)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef99a60c0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef99a61e0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef99a69c0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef99a6ae0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef99a6f60)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef99a7080)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef99a73e0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef99a7500)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef99a4140)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef99a7860)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef99a7bc0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef99a7ce0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef999d960)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef999d840)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef999dde0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef999df00)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef999e260)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef999e380)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef999e140)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef999e800)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef999eec0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef999f100)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef999f6a0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef999f220)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef999fd60)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef999fe80)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef99a01e0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef99a0300)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef9922860)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef9922ce0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef995c490)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef995c6d0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef995cd90)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef995cfd0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef995d690)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef995d8d0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef995df90)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef995b8c0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef995bd40)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef995c1c0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef995fe70)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef9960530)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef9961190)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef99613d0)
Oct 28 22:56:50 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef9961610)
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef9961cd0)
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef9962390)
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55bef9a21310 (res 0x55bef99625d0)
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55bef9a21310
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55bef9a21310 (res 0x55bef98f31a0)
Oct 28 22:56:51 steamdeck gamescope-session[9040]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55bef9a21310
```

</details>

**Comment by matte-schwartz** [comment]
Was able to narrow down the issue quite a bit, major difference seems to be in how "Mouse Region" Steam Input events (or "Cursor", which is Grim Dawn's default right trackpad UI binding) get treated for presentation by gamescope with a visible cursor vs how "As Mouse" Steam Input events get treated for presentation.

Mouse Region events went from always showing a visible cursor in a similar manor to "As Mouse" to only showing a visible cursor for the 3000ms timeout set in `/usr/bin/gamescope-session` despite continued interaction. 

This lines up with what was reported by another user: https://github.com/ValveSoftware/SteamOS/issues/1681#issuecomment-2456367890 but in Diablo II Resurrected

**Comment by ubeogesh** [comment]
A workaround for this is binding right pad *touch* to "Mouse > Move Cursor by amount > 1 in X or Y", then go to settings and enable "hold to repeat (turbo)".

These "move by amount" events force the cursor to always be shown.

**Comment by matte-schwartz** [comment]
from my digging today, I'm almost certain the issue lies somewhere in the handling of MouseCursor but I've unfortunately not made much progress in terms of fixing things.

debugging patch for the logs below: https://gist.github.com/matte-schwartz/91a2f601e55dd890bc5041abbdb0476a (ignore log_xcursor, thats irrelevant here)

<details><summary>when using "Cursor" or "Mouse Region" in Steam Input:</summary>

```
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: Got commit not for current surface.
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: MouseCursor_Constrained::UpdatePosition: x=1099 y=419
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55f3df0a8e80
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55f3df0a8e80 (res 0x55f3df0a1c80)
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55f3df0a8e80
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: MouseCursor_NonConstrained::UpdatePosition: x=1099 y=419
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55f3df0a8e80
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55f3df0a9090 (res 0x55f3df0a7c50)
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55f3df0a9090
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: Got commit not for current surface.
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: MouseCursor_Constrained::UpdatePosition: x=1118 y=421
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55f3df0a9090
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55f3df0a9090 (res 0x55f3df0a7c50)
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55f3df0a9090
Nov 14 15:38:20 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: MouseCursor_NonConstrained::UpdatePosition: x=1118 y=421
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: MouseCursor_NonConstrained::UpdatePosition: x=1118 y=421
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55f3df0a9090
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55f3df0a9010 (res 0x55f3df0a7c50)
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55f3df0a9010
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: Got commit not for current surface.
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: MouseCursor_Constrained::UpdatePosition: x=1146 y=423
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55f3df0a9010
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55f3df0a90c0 (res 0x55f3df0a7c50)
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55f3df0a90c0
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: MouseCursor_NonConstrained::UpdatePosition: x=1146 y=423
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55f3df0a90c0
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55f3df0a91a0 (res 0x55f3df0a6e10)
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55f3df0a91a0
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: Got commit not for current surface.
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: MouseCursor_Constrained::UpdatePosition: x=1165 y=423
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55f3df0a91a0
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55f3df0a91a0 (res 0x55f3df0a6e10)
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55f3df0a91a0
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: MouseCursor_NonConstrained::UpdatePosition: x=1165 y=423
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55f3df0a91a0
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new locked_pointer 0x55f3df0a9250 (res 0x55f3df0a1c80)
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55f3df0a9250
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: Got commit not for current surface.
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: MouseCursor_Constrained::UpdatePosition: x=1172 y=422
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55f3df0a9250
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55f3df0a9250 (res 0x55f3df0a1c80)
Nov 14 15:38:21 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55f3df0a9250
```


</details>

you can see it constantly bounce between MouseCursor_Constrained and MouseCursor_NonConstrained, but neither of which draws a cursor consistently, and the pointer events don't get picked up and forwarded from wl_server -> gamescope_ei

<details><summary>when using "Mouse" or "Joystick Mouse" in Steam Input: (or while holding the "Steam" hotkey)</summary>

```
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:46] destroying constraint 0x55f3df067a30
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x55f3df067a10 (res 0x55f3defa6a90)
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: [types/wlr_pointer_constraints_v1.c:378] constrained 0x55f3df067a10
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: Got commit not for current surface.
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: wlserver_perform_rel_pointer_motion -9.000000 3.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: Mouse motion -9.000000 3.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] gamescope_ei: Pointer motion: -9.000000 3.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: wlserver_perform_rel_pointer_motion -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: Mouse motion -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] gamescope_ei: Pointer motion: -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: MouseCursor_NonConstrained::UpdatePosition: x=1148 y=430
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: wlserver_perform_rel_pointer_motion -8.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: Mouse motion -8.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] gamescope_ei: Pointer motion: -8.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: wlserver_perform_rel_pointer_motion -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: Mouse motion -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] gamescope_ei: Pointer motion: -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: wlserver_perform_rel_pointer_motion -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: Mouse motion -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] gamescope_ei: Pointer motion: -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: wlserver_perform_rel_pointer_motion -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: Mouse motion -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] gamescope_ei: Pointer motion: -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: MouseCursor_NonConstrained::UpdatePosition: x=1113 y=438
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: wlserver_perform_rel_pointer_motion -8.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: Mouse motion -8.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] gamescope_ei: Pointer motion: -8.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: wlserver_perform_rel_pointer_motion -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: Mouse motion -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] gamescope_ei: Pointer motion: -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: wlserver_perform_rel_pointer_motion -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: Mouse motion -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] gamescope_ei: Pointer motion: -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: wlserver_perform_rel_pointer_motion -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: Mouse motion -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] gamescope_ei: Pointer motion: -9.000000 2.000000
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] xwm: MouseCursor_NonConstrained::UpdatePosition: x=1078 y=446
Nov 14 15:41:17 legion-go gamescope-session[39720]: [gamescope] [Debug] wlserver: wlserver_perform_rel_pointer_motion -9.000000 2.000000
```

</details>

you can see here that only MouseCursor_NonConstrained gets called, and the pointer is properly forwarded and drawn from wl_server -> gamescope_ei

**Comment by matte-schwartz** [comment]
As an experiment, I am able to at least get a visible cursor again in the absolute silliest way possible, by changing `EIS_EVENT_POINTER_MOTION_ABSOLUTE` to use `wlserver_mousemotion` instead of `wlserver_mousewarp` in InputEmulation.cpp, but this is just a quick and dirty hack that breaks cursor movement with Mouse Region. 

given this, it seems like we should probably look at `wlserver_mousewarp` to see if there's anything in there that makes sense as to why it does not draw a cursor in the same way `wlserver_mousemotion` does, but so far i'm coming up empty

**Comment by matte-schwartz** [comment]
getting closer:

removing the single line here https://github.com/ValveSoftware/gamescope/blob/master/src/wlserver.cpp#L2378 will at the very least properly re-draw both kinds of mouse movement (mousemotion/mousewarp). 

that's probably about as far as I can go with debugging this since I truly do not understand why removing that check fixes the draw logic for Mouse Region/Cursor

**Comment by JonathanTheDev** [comment]
We have the same issue with our game Necesse. After updating the Steam Deck the cursor no longer shows when playing from Steam. Necesse doesn't show the cursor until it has finished loading, so I don't know if it's shown for 3000 ms. But when holding down the "Steam" button to force the cursor to show, it seams to disappear again after about 3-4 seconds.

**Comment by matte-schwartz** [comment]
Got a report this is still happening in Necesse from one of the game's developers here: https://github.com/ValveSoftware/SteamOS/issues/1723#issuecomment-2700395040

**Comment by hron** [comment]
I have just tested the preview and at least the issue I had is fixed! For me the cursor was always missing when I used Steam Controller with mouse emulation while playing any game via Remote Play. I have tested Dyson Sphere Program and the cursor doesn't become invisible anymore when I launch it via Remote Play and try to use Steam Controller.

**Comment by Revmatek** [comment]
@matte-schwartz @JonathanTheDev 
Is this fixed in the beta branch now?:
https://steamcommunity.com/app/1675200/eventcomments/595142635297973590

This looks similar to an issues I reported that was fixed by this:
https://github.com/ValveSoftware/gamescope/commit/cc15bf613d39ee8793829d640813c7898dcc8a47

**Comment by JonathanTheDev** [comment]
> [@matte-schwartz](https://github.com/matte-schwartz) [@JonathanTheDev](https://github.com/JonathanTheDev) Is this fixed in the beta branch now?: https://steamcommunity.com/app/1675200/eventcomments/595142635297973590

The issue is sadly still present in Necesse. See my comment here: https://github.com/ValveSoftware/SteamOS/issues/1723#issuecomment-2700395040

**Comment by Revmatek** [comment]
> > [@matte-schwartz](https://github.com/matte-schwartz) [@JonathanTheDev](https://github.com/JonathanTheDev) Is this fixed in the beta branch now?: https://steamcommunity.com/app/1675200/eventcomments/595142635297973590
> 
> The issue is sadly still present in Necesse. See my comment here: [ValveSoftware/SteamOS#1723 (comment)](https://github.com/ValveSoftware/SteamOS/issues/1723#issuecomment-2700395040)

Bummer. I had to update the beta branch and restart twice to pickup the fix. The first time to switch the branch, then I had to check for updates and apply.
