### ISSUE TITLE
Hang on startup after bd722f786f5a74f8282d903bd5eb3d331c4cd920 on NV

### ISSUE THREAD

**Issue by Joshua-Ashton** [ValveSoftware/gamescope#948]
Hangs on startup on NVIDIA after https://github.com/ValveSoftware/gamescope/commit/bd722f786f5a74f8282d903bd5eb3d331c4cd920

Note that this is not with any of the reshade stuff enabled.

Not sure what is bad about this commit. The log says its grabbing 2 as the async compute queue and 0 as the general one.

Seems like we hang in a `CVulkanDevice::wait`, despite not ever using the general queue anywhere at all. Seems like merely grabbing both queues here seems to break `vkWaitSemaphores`.

**Comment by Joshua-Ashton** [comment]
Nothing interesting in validation...

**Comment by Joshua-Ashton** [comment]
cc: @erik-kz given you have been looking at stuff recently.

**Comment by cubanismo** [comment]
I've filed internal bug 4330963 to track investigation within NVIDIA.

**Comment by r3k2** [comment]
same issue here with wayland+wlroots+sway+nvidia on Arch GNU/Linu 
```
 gamescope 
wlserver: [backend/headless/backend.c:68] Creating headless backend
vulkan: physical device 10de:1b06 compute queue doesn't support presenting on our surface, using graphics queue
vulkan: selecting physical device 'NVIDIA GeForce GTX 1080 Ti': queue family 0 (general queue family 0)
vulkan: physical device supports DRM format modifiers
Segmentation fault
```
this was working fine before.

**Comment by HWG90** [comment]
Issue continues in 3.13.8

**Comment by sharkautarch** [comment]
> Issue continues in 3.13.8

@HWG90 
I've just updated my [nvidia-fix](https://github.com/sharkautarch/gamescope/tree/nvidia-fix) branch, which has a workaround for the current nvidia driver bug w/ gamescope, to the latest git revision of gamescope.
I've tested my building and running gamescope from my branch w/ nvidia, and it seems to work as long as you set ENABLE_GAMESCOPE_WSI=0 (e.i. `ENABLE_GAMESCOPE_WSI=0 gamescope <params> -- <game>`)
if you're using hybrid graphics, you'll have to run gamescope like so: `ENABLE_GAMESCOPE_WSI=0 gamescope --prefer-vk-device $(env MESA_VK_DEVICE_SELECT=list vulkaninfo) <params> -- <game>`

to build from my branch:

```
git clone https://github.com/sharkautarch/gamescope.git
cd gamescope
git checkout nvidia-fix
meson setup -Dc_args="-Wno-uninitialized -Wno-maybe-uninitialized" -Dcpp_args="-Wno-uninitialized -Wno-maybe-uninitialized" --reconfigure build
ninja -C build
meson install -C build
```

**Comment by ReillyBrogan** [comment]
I would note that that revert breaks gamescope on AMD cards at least, and likely Intel ones as well. In Solus we handled this by building 3.13.8 twice, once with the Nvidia revert applied and once without. The Nvidia revert build is installed at `/usr/bin/gamescope-nvidia` while the unpatched build is at `/usr/bin/gamescope`. Just a though on how to handle this if there are any other distribution maintainers watching this thread.

**Comment by akay** [comment]
> to build from my branch:

Thank you for providing this. `vkcube` now starts, but it stops after a few seconds and after (always) 30 seconds later, I get the following in the terminal:

`vblankmanager: write failed: Resource temporarily unavailable`

**Comment by ElecTwix** [comment]
> > to build from my branch:
> 
> Thank you for providing this. `vkcube` now starts, but it stops after a few seconds, then after exactly 30 seconds later, I get the following spammed forever in the terminal until I SIGKILL gamescope-wl:
> 
> `vblankmanager: write failed: Resource temporarily unavailable`

Same behavior here too.
```
OS: Arch Linux x86_64
NV Driver Version: 535.129.03

**Comment by sharkautarch** [comment]
> > > to build from my branch:
> > 
> > 
> > Thank you for providing this. `vkcube` now starts, but it stops after a few seconds, then after exactly 30 seconds later, I get the following spammed forever in the terminal until I SIGKILL gamescope-wl:
> > `vblankmanager: write failed: Resource temporarily unavailable`
> 
> Same behavior here too.
> 
> ```
> OS: Arch Linux x86_64
> NV Driver Version: 535.129.03
> ```



Try running it with:
`ENABLE_GAMESCOPE_WSI=0 gamescope --prefer-vk-device  “10de:$(vulkaninfo -o /dev/stdout | grep -i 10de -A1 | tail -n 1 | tr ‘x’ ‘ ‘ | awk ‘{print $4}’)” <params> — <game>`


You could also try building from my 
`nvidia-fix-and-vblank-debug-extra-experimental-v4.5` idk if said branch would work if nvidia-fix branch doesn’t for you

**Comment by akay** [comment]
> Try running it with:

I have tried using the `--prefer-vk-device` flag before, sadly it still doesn't work.

> nvidia-fix-and-vblank-debug-extra-experimental-v4.5

The new branch doesn't seem to work either.

**Comment by sharkautarch** [comment]
> > Try running it with:
> 
> I have tried using the `--prefer-vk-device` flag before, sadly it still doesn't work.
> 
> > nvidia-fix-and-vblank-debug-extra-experimental-v4.5
> 
> The new branch doesn't seem to work either.

Huh, strange…
Can you provide the terminal output of gamescope (up until it just repeatedly outputs `vblankmanager: write failed: Resource temporarily unavailable`)

Also are you also using 535 nvidia drivers? (Those are what I’m using right now, tho I’m currently specifically on the 6.6 Linux kernel w/ the 535 dkms nvidia drivers)

Hmmm I feel like I’ve seen that `vblankmanager: write failed: Resource temporarily unavailable` message before, but I don’t remember the context for it…

**Comment by akay** [comment]
I've updated my last comment, and the rest:

```
$ pacman -Q nvidia-dkms
nvidia-dkms 545.29.06-1

$ uname -a
Linux artsql 6.6.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 20 Nov 2023 23:18:21 +0000 x86_64 GNU/Linux

$ cat /proc/cmdline
... nvidia-drm.modeset=1 loglevel=3 sysrq_always_enabled=1 udev.log_level=3 bgrt_disable
```

**Comment by sharkautarch** [comment]
> I've updated my last comment, and the rest:
> 
> ```
> $ pacman -Q nvidia-dkms
> nvidia-dkms 545.29.06-1
> 
> $ uname -a
> Linux artsql 6.6.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 20 Nov 2023 23:18:21 +0000 x86_64 GNU/Linux
> 
> $ cat /proc/cmdline
> ... nvidia-drm.modeset=1 loglevel=3 sysrq_always_enabled=1 udev.log_level=3 bgrt_disable
> ```

hmmm well I’m using nvidia-dkms 535
Maybe the ‘nvidia-fix’ branch doesn’t work with nvidia 545 drivers…?
I’ve had to stay on the nvidia-dkms 535 drivers, because 545 didn’t seem to work well on my hybrid graphics laptop so idk

**Comment by akay** [comment]
> Did you also try running it with
> `--prefer-vk-device “10de:$(vulkaninfo -o /dev/stdout | grep -i 10de -A1 | tail -n 1 | tr ‘x’ ‘ ‘ | awk ‘{print $4}’)”`

That just outputs `1f07` which is what I tried before.

Small nitpick: Please make sure to convert your backticks and backquotes to ticks and quotes when asking to run commands :)

**Comment by akay** [comment]
> hmmm well I’m using nvidia-dkms 535

Okay, it works using 535:
```
$ pacman -Q nvidia-dkms
nvidia-dkms 535.113.01-2

$ ENABLE_GAMESCOPE_WSI=0 gamescope -w 2560 -h 1440 -e -- steam
```
So the problem _is_ with how the 545 series of drivers handle things.

Can confirm that both your branches (`nvidia-fix` and `nvidia-fix-and-vblank-debug-extra-experimental-v4.5`) work.

Not perfectly, but I can actually load Half-Life 2 and a few other games, using `GE_Proton8_24` where needed.

Guess we'll just have to wait for @cubanismo to hopefully fix it internally :)

**Comment by sharkautarch** [comment]
> Can confirm that both your branches (`nvidia-fix` and `nvidia-fix-and-vblank-debug-extra-experimental-v4.5`) work.
> 
> Not perfectly, but I can actually load Half-Life 2 and a few other games, using `GE_Proton8_24` where needed.


try my newer `nvidia-fix-and-vblank-debug-extra-experimental-v4.6` branch

**Comment by SeongGino** [comment]
> good to hear that it works for you on 535
> 
> > Can confirm that both your branches (`nvidia-fix` and `nvidia-fix-and-vblank-debug-extra-experimental-v4.5`) work.
> > Not perfectly, but I can actually load Half-Life 2 and a few other games, using `GE_Proton8_24` where needed.
> 
> @akay try my newer `nvidia-fix-and-vblank-debug-extra-experimental-v4.6` branch

Using 545, it does seem to work with both OGL and Vulkan (Wine/DXVK) games.

**Comment by sharkautarch** [comment]
> > good to hear that it works for you on 535
> > > Can confirm that both your branches (`nvidia-fix` and `nvidia-fix-and-vblank-debug-extra-experimental-v4.5`) work.
> > > Not perfectly, but I can actually load Half-Life 2 and a few other games, using `GE_Proton8_24` where needed.
> > 
> > 
> > @akay try my newer `nvidia-fix-and-vblank-debug-extra-experimental-v4.6` branch
> 
> Using 545, it does seem to work with both OGL and Vulkan (Wine/DXVK) games.


Huh, maybe there was a really new update to 545 that unbroke whatever was causing an issue? idk

Can you run `nvidia-smi` after running gamescope to confirm that gamescope is using the nvidia gpu w/ your 545 driver?

**Comment by SeongGino** [comment]
> Can you run `nvidia-smi` after running gamescope to confirm that gamescope is using the nvidia gpu w/ your 545 driver? (Just checking that it isn't just using a different gpu in the case that your system has another non-nvidia gpu)

If this is a reply to me, it's a desktop with only a 3060ti for graphics (no APU or iGPU at all).

**Comment by akay** [comment]
> try my newer `nvidia-fix-and-vblank-debug-extra-experimental-v4.6` branch

Things are more or less OK with 535 and `nvidia-fix`, you want me to try this branch with 545?

**Comment by sharkautarch** [comment]
> > try my newer `nvidia-fix-and-vblank-debug-extra-experimental-v4.6` branch
> 
> Things are more or less OK with 535 and `nvidia-fix`, you want me to try this branch with 545?


no just try the `nvidia-fix-and-vblank-debug-extra-experimental-v4.6` branch w/ nvidia 535
the v4.6 might just feel a bit smoother for you (tho it might not be noticable)

**Comment by akay** [comment]
Sure, it feels OK :) Thank you!

**Comment by sharkautarch** [comment]
> @sharkautarch I'm just testing `nvidia-fix-and-vblank-debug-extra-experimental-v4.7` because I also encounter `vblankmanager: write failed: Resource temporarily unavailable` errors.
> 
> I got an STL exception from `std::clamp` with `!(__hi < __lo)`, so I've replaced the debugging calls with a custom `safe_clamp`:
> 
> ```c++
> template<class T>
> constexpr const T& safe_clamp(const T& v, const T& lo, const T& hi)
> {
>     if (lo > hi) {
>            std::cout << "lo > hi" << lo << " " << hi << "; returning lo\n";
>            return lo;
>     }
>     return std::clamp(v, lo, hi);
> }
> ```
> 
> And now I get many of these
> 
> ```
> lo > hi16666666 7638888; returning lo
> lo > hi18316666 8333332; returning lo
> lo > hi16414964 7638888; returning lo
> lo > hi18064964 7291666; returning lo
> ```
> 
> which are probably not very helpful because I don't see which call these come from, but I just thought you might be interested in knowing about this STL exception.


Do you know which gamescope cpp file is generating these exceptions from? (or is calling whatever STL function/method that then produces these exceptions?)  
If you don't, you should be able to figure it out by:
- first making sure your linux OS is set to dump coredumps:
```
if ! grep -qi 'kernel.core_pattern' /etc/sysctl.conf; then
  sudo sh -c 'echo "kernel.core_pattern=core.%p.%u.%s.%e.%t" >> /etc/sysctl.conf'
  sudo sysctl -p
fi
ulimit -c unlimited
```  

- run gamescope again to generate the core dump for the STL exception
- run `ls -lt | less` and you should see a file that starts with the word `core` near/at the top
- if you're on a distro like arch, make sure you have the `debuginfod` package installed
- Analyze the core dump with gdb:
`gdb <path/to/gamescope-binary> ./<core dump file>`

- get a backtrace by entering:
 `bt`
 or:
 `thread apply all bt`
let me know what you find from that
see also: https://linuxconfig.org/gdb-debugging-tutorial-for-beginners

**Comment by jkozera** [comment]
```
#4  0x00007f9c5a8dd3b2 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*)
    (file=file@entry=0x55e2052b2008 "/usr/include/c++/13.2.1/bits/stl_algo.h", line=line@entry=3669, function=function@entry=0x55e2052b1fa8 "constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = long int]", condition=condition@entry=0x55e2052c1adb "!(__hi < __lo)") at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/debug.cc:61
#5  0x000055e20518f7e2 in std::clamp<long>(long const&, long const&, long const&) (__val=<optimized out>, __lo=<optimized out>, __hi=<optimized out>) at /usr/include/c++/13.2.1/bits/stl_algo.h:3667
#6  std::clamp<long>(long const&, long const&, long const&) (__hi=<optimized out>, __lo=<optimized out>, __val=<optimized out>) at /usr/include/c++/13.2.1/bits/stl_algo.h:3667
#7  vblankThreadRun(bool, bool, long, long double) (neverBusyWait=<optimized out>, alwaysBusyWait=<optimized out>, cpu_pause_time_len=<optimized out>, nsPerTick_long=<optimized out>)
    at ../src/vblankmanager.cpp:773
```
so it's this one:
```
                        rollingMaxDrawTime = (uint64_t)std::clamp(centered_mean/2, (long int) rollingMaxDrawTime, nsecInterval + nsecInterval/10);
```

**Comment by sharkautarch** [comment]
> ```
> #4  0x00007f9c5a8dd3b2 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*)
>     (file=file@entry=0x55e2052b2008 "/usr/include/c++/13.2.1/bits/stl_algo.h", line=line@entry=3669, function=function@entry=0x55e2052b1fa8 "constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = long int]", condition=condition@entry=0x55e2052c1adb "!(__hi < __lo)") at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/debug.cc:61
> #5  0x000055e20518f7e2 in std::clamp<long>(long const&, long const&, long const&) (__val=<optimized out>, __lo=<optimized out>, __hi=<optimized out>) at /usr/include/c++/13.2.1/bits/stl_algo.h:3667
> #6  std::clamp<long>(long const&, long const&, long const&) (__hi=<optimized out>, __lo=<optimized out>, __val=<optimized out>) at /usr/include/c++/13.2.1/bits/stl_algo.h:3667
> #7  vblankThreadRun(bool, bool, long, long double) (neverBusyWait=<optimized out>, alwaysBusyWait=<optimized out>, cpu_pause_time_len=<optimized out>, nsPerTick_long=<optimized out>)
>     at ../src/vblankmanager.cpp:773
> ```
> 
> so it's this one:
> 
> ```c++
> rollingMaxDrawTime = (uint64_t)std::clamp(centered_mean/2, (long int) rollingMaxDrawTime, nsecInterval + nsecInterval/10);
> ```


I just realized that I ordered the parameters to std::clamp wrong lol

I just fixed all of the std::clamp and pushed out the fix to the `nvidia-fix-and-vblank-debug-extra-experimental-v4.7` branch

Thanks for spotting that!

**Comment by jkozera** [comment]
Now it seems better, because it runs for a bit longer time, but it still crashes, in the same line. Maybe it's because of larger latency occuring? Because it crashes shortly after `VBlankTimeInfo_t receive latency: 2.42ms` while previous latencies were on order of 0.01ms.

**Comment by ageisen2000** [comment]
> > Replying to [#948 (comment)](https://github.com/ValveSoftware/gamescope/issues/948#issuecomment-1837594631)
> 
> I just realized that I ordered the parameters to std::clamp wrong lol
> 
> I just fixed all of the std::clamp and pushed out the fix to the `nvidia-fix-and-vblank-debug-extra-experimental-v4.7` branch
> 
> Thanks for spotting that!
> 
> also let me know if there are still any issues with `nvidia-fix-and-vblank-debug-extra-experimental-v4.7`

Can you tell me how to fix this error  when building from your branch? I have a 3090 and would like to try this fix with the newest nvidia drivers
`src/meson.build:95:18: ERROR: Include dir reshade/source does not exist.`

**Comment by sharkautarch** [comment]
> > > Replying to [#948 (comment)](https://github.com/ValveSoftware/gamescope/issues/948#issuecomment-1837594631)
> > 
> > 
> > I just realized that I ordered the parameters to std::clamp wrong lol
> > I just fixed all of the std::clamp and pushed out the fix to the `nvidia-fix-and-vblank-debug-extra-experimental-v4.7` branch
> > Thanks for spotting that!
> > also let me know if there are still any issues with `nvidia-fix-and-vblank-debug-extra-experimental-v4.7`
> 
> Can you tell me how to fix this error when building from your branch @sharkautarch? I have a 3090 and would like to try this fix with the newest nvidia drivers `src/meson.build:95:18: ERROR: Include dir reshade/source does not exist.`
> 
> I'm running this command:
> 
> ```
> meson setup -Dc_args="-Wno-uninitialized -Wno-maybe-uninitialized" -Dcpp_args="-Wno-uninitialized -Wno-maybe-uninitialized" --reconfigure build
> ```

I believe you just need to also run
`git submodule update --init --recursive`
and then run
`ninja -C build` again

**Comment by ageisen2000** [comment]
@sharkautarch, this is probably a dumb question.... but where do I get the binary that was built? How do run the `gamescope` command with it?

**Comment by ageisen2000** [comment]
@sharkautarch, do you know if this patch would cause artifacting issues on Nvidia cards? I can't launch my game without a lot of artifacting / glitchy graphics.

**Comment by sharkautarch** [comment]
> @sharkautarch, do you know if this patch would cause artifacting issues on Nvidia cards? I can't launch my game without a lot of artifacting / glitchy graphics.


For which? `nvidia-fix` or `nvidia-fix-and-vblank-debug-extra-experimental-v4.7`?

Well for either case, try my new branch:
`nvidia-fix-and-vblank-debug-extra-experimental-v4.8`

**Comment by ageisen2000** [comment]
I was using the 4.7 patch. I'll try 4.8 tonight and let you know how it
goes

**Comment by ageisen2000** [comment]
@sharkautarch , the 4.8 branch seems to have crashed my computer when I ran it from a TTY. I couldn't swap TTYs and I didn't see any logs or anything. 
Command I ran:
`gamescope -W 3440 -H 1440 --immediate-flips -O DP-1 -e -- steam`

**Comment by detiam** [comment]
I'm on driver 545, and with branch `nvidia-fix-and-vblank-debug-extra-experimental-v4.8` I can run gamescope on nested mode (under X) perfectly, on embedded mode (under tty) without option `--immediate-flips` or `--adaptive-sync` it works fine, with these option gamescope will freeze, but program still running, and my monitor shows it only have 48hz refresh rate.
[log.txt](https://github.com/ValveSoftware/gamescope/files/13625490/log.txt)

**Comment by sharkautarch** [comment]
I'm not surprised that gamescope still crashing with certain options with nvidia..
I might try compiling gamescope w/ clang sanitizers and vulkan validation and see if I find anything that pops up when using `--immediate-flips` or `--adaptive-sync`

**Comment by ageisen2000** [comment]
> I'm not surprised that gamescope still crashing with certain options with nvidia.. I might try compiling gamescope w/ clang sanitizers and vulkan validation and see if I find anything that pops up when using `--immediate-flips` or `--adaptive-sync`
> 
> EDIT: does anything change if you add the environment variable `ENABLE_GAMESCOPE_WSI=0 gamescope --immediate-flips ...` ?

When I enable that environment variable it actually loads up.

Gets stuck on this glitchy screen though 
![PXL_20231210_011000420 MP](https://github.com/ValveSoftware/gamescope/assets/8844888/75a48dde-4712-4b0e-81a6-a16c2fb19e2d)

**Comment by sharkautarch** [comment]
maybe try running `export VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation ENABLE_GAMESCOPE_WSI=0 gamescope --immediate-flips ...` and see if it prints anything else useful (you might need to add `> some_file.out` at the end so that you'll be able to see what it printed out)

**Comment by detiam** [comment]
> maybe try running `export VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation ENABLE_GAMESCOPE_WSI=0 gamescope --immediate-flips ...` and see if it prints anything else useful (you might need to add `> some_file.out` at the end so that you'll be able to see what it printed out)

[log.txt](https://github.com/ValveSoftware/gamescope/files/13626305/log.txt) with command 
```
VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation ENABLE_GAMESCOPE_WSI=0 gamescope --adaptive-sync -- vkcube > log.txt 2>&1
```
it will first load up, show vkcube spin for one second then freeze, monitor shows 48 refresh rate, when I press `esc` vkcube will exit and gamescope exit.

**Comment by ageisen2000** [comment]
I ran
```sh
sudo setcap 'CAP_SYS_NICE=eip' /usr/local/bin/gamescope
VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation ENABLE_GAMESCOPE_WSI=0 gamescope -W 3440 -H 1440 -r 175 --immediate-flips -O DP-2 -- glxgears > glxgearsout.log
```

And got a bunch of garbage on the screen. I could see the app, but weirdly enough even in TTY mode I saw a steam window. Idk whats going on there.

[glxgearsout.log](https://github.com/ValveSoftware/gamescope/files/13626812/glxgearsout.log)

**Comment by sharkautarch** [comment]
> I ran
> 
> ```shell
> sudo setcap 'CAP_SYS_NICE=eip' /usr/local/bin/gamescope
> VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation ENABLE_GAMESCOPE_WSI=0 gamescope -W 3440 -H 1440 -r 175 --immediate-flips -O DP-2 -- glxgears > glxgearsout.log
> ```
> 
> And got a bunch of garbage on the screen. I could see the app, but weirdly enough even in TTY mode I saw a steam window. Idk whats going on there.
> 
> [glxgearsout.log](https://github.com/ValveSoftware/gamescope/files/13626812/glxgearsout.log)



I think there's also an issue with running gamescope w/ nvidia after setting 'CAP_SYS_NICE=eip' tho I think I might be able to find a workaround to that specifically

For `--immediate-flips`, I'm guessing that it probably won't be able to work, or that is, even if we could find a way to prevent gamescope on nvidia from crashing when using it, it'll probably just do nothing. Just gotta hope that it'll be patched in an nvidia driver update... fingers crossed

If you want to try to reduce latency, try running gamescope w/  `MESA_VK_WSI_PRESENT_MODE=mailbox ENABLE_GAMESCOPE_WSI=0 gamescope ...` or  `MESA_VK_WSI_PRESENT_MODE=mailbox ENABLE_GAMESCOPE_WSI=0 gamescope ... -- env MESA_VK_WSI_PRESENT_MODE=immediate ...`

**Comment by unhappy-ending** [comment]
Hello, just adding some feedback. I could run nvidia+gamescope on anything that was native wayland apps just fine. Problem was anything using Xwayland would give me a black screen. I installed the 535.43.20 vulkan beta driver @brain-anti-freeze posted about earlier and it fixed gamescope for me. I'm not using the @sharkautarch nvidia-fix patch, just vanilla gamescope from the Gentoo repo.

**Comment by brain-anti-freeze** [comment]
@unhappy-ending are you running embedded ? (If so is that in an X or an Wayland session)

**Comment by sharkautarch** [comment]
> Hello, just adding some feedback. I could run nvidia+gamescope on anything that was native wayland apps just fine. Problem was anything using Xwayland would give me a black screen. I installed the 535.43.20 vulkan beta driver @brain-anti-freeze posted about earlier and it fixed gamescope for me. I'm not using the @sharkautarch nvidia-fix patch, just vanilla gamescope from the Gentoo repo.


W/ vanilla gamescope, try launching whatever Xwayland app w/: `ENABLE_GAMESCOPE_WSI=0 gamescope ... - <xwayland app>`

**Comment by SeongGino** [comment]
FWIW, the `nvidia-vulkan` version of the driver on Arch can handle vanilla gamescope just fine (though in my case it still needs `__GL_THREADED_OPTIMIZATIONS=0` prepended to the gamescope command). Presumably this would be resolved when this hits the next stable nv driver?

**Comment by sharkautarch** [comment]
> FWIW, the `nvidia-vulkan` version of the driver on Arch can handle vanilla gamescope just fine (though in my case it still needs `__GL_THREADED_OPTIMIZATIONS=0` prepended to the gamescope command). Presumably this would be resolved when this hits the next stable nv driver?


Ah good to hear! Do you know if gamescope WSI also works with that driver (if you don't have to specify ENABLE_GAMESCOPE_WSI=0 for vanilla gamescope to work, then that would mean that gamescope WSI is indeed working)?

**Comment by SeongGino** [comment]
> > FWIW, the `nvidia-vulkan` version of the driver on Arch can handle vanilla gamescope just fine (though in my case it still needs `__GL_THREADED_OPTIMIZATIONS=0` prepended to the gamescope command). Presumably this would be resolved when this hits the next stable nv driver?
> 
> Ah good to hear! Do you know if gamescope WSI also works with that driver (if you don't have to specify ENABLE_GAMESCOPE_WSI=0 for vanilla gamescope to work, then that would mean that gamescope WSI is indeed working)?

### WAIT, ABORT

I had a stale build of your nvidia-fix fork in `/usr/local/bin` in the way.

Taking that off and using upstream for real, I'm seeing a gamescope window open, then nothing--the window graphic is effectively frozen and the application inoperable, even with `ENABLE_GAMESCOPE_WSI=0` set.

My bad.

**Comment by sharkautarch** [comment]
> > > FWIW, the `nvidia-vulkan` version of the driver on Arch can handle vanilla gamescope just fine (though in my case it still needs `__GL_THREADED_OPTIMIZATIONS=0` prepended to the gamescope command). Presumably this would be resolved when this hits the next stable nv driver?
> > 
> > 
> > Ah good to hear! Do you know if gamescope WSI also works with that driver (if you don't have to specify ENABLE_GAMESCOPE_WSI=0 for vanilla gamescope to work, then that would mean that gamescope WSI is indeed working)?
> 
> ### WAIT, ABORT
> 
> I had a stale build of your nvidia-fix fork in `/usr/local/bin` in the way.
> 
> Taking that off and using upstream for real, I'm seeing a gamescope window open, then nothing--the window graphic is effectively frozen and the application inoperable, even with `ENABLE_GAMESCOPE_WSI=0` set.
> 
> My bad. To clarify: it was your fork that still works, but upstream gamescope doesn't.


oh what a turn of events, lol!
no worries

**Comment by tylerfan** [comment]
NVIDIA-SMI 535.129.03  
tried the nvidia-fix branch, still seg fault on gnome wayland ubuntu23.10.

**Comment by sharkautarch** [comment]
> NVIDIA-SMI 535.129.03 tried the nvidia-fix branch, still seg fault on gnome wayland ubuntu23.10.


Please post a link to a github gist/pastebin of the terminal output of you got + the exact command you ran

**Comment by tylerfan** [comment]
git branch vblank-debug-extra-experimental-v4.8
command: ./gamescope vk-cube
output:
```
wlserver: [backend/headless/backend.c:67] Creating headless backend
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
vulkan: physical device 10de:2216 compute queue doesn't support presenting on our surface, using graphics queue
vulkan: selecting physical device 'NVIDIA GeForce RTX 3080': queue family 0 (general queue family 0)
vulkan: physical device supports DRM format modifiers
Segmentation fault (core dumped)
```

**Comment by sharkautarch** [comment]
> git branch vblank-debug-extra-experimental-v4.8 command: ./gamescope vk-cube output:
> ...

OHHHH yeah you're using the wrong branch for nvidia
use `nvidia-fix-vblank-debug-extra-experimental-v4.8` instead of `vblank-debug-extra-experimental-v4.8` (the latter I made for checking how the code I had written works on an intel igpu)

**Comment by tylerfan** [comment]
falling back to 525, the error is now this:
```
wlserver: [backend/headless/backend.c:67] Creating headless backend
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
vulkan: physical device 10de:2216 compute queue doesn't support presenting on our surface, using graphics queue
vulkan: selecting physical device 'NVIDIA GeForce RTX 3080': queue family 0
vulkan: physical device supports DRM format modifiers
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x3231564E (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x48344241 (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x48344258 (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344241 (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344258 (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   RG16 (0x36314752)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
vulkan: Creating Gamescope nested swapchain with format 44 and colorspace 0
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:17] Starting headless backend
wlserver: [xwayland/server.c:108] Starting Xwayland on :0
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x559991e44a10 (res 0x559991ffeae0)
wlserver: [xwayland/server.c:273] Xserver is ready
x86_64 processor:
   Brand: AuthenticAMD
   Model: AMD Ryzen Threadripper PRO 3945WX 12-Cores
   Invariant TSC: True
   cpuid leaf 15H is not supported
   From measurement frequency   3.99 GHz => 250.47 ps
   Sanity check against std::chrono::steady_clock gives frequency   3.99 GHz => 250.47 ps
Measured granularity = 1 tick =>   3.99 GHz, 250.47 ps
nsPerTick: 0.250474
rollingMaxDrawTime: 3000000
rollingMaxDrawTime after using std::clamp: 8333333
offset: 9983333 sleep_cycle: 
vblank cycle time before first sleep: 0.030497ms
rollingMaxDrawTime after using std::clamp: 8333333
offset: 9983333 sleep_cycle: 
vblank cycle time before second wait: 7.80868ms
xwm: execvp failed: No such file or directory
vblank cycle time before write(): 10.0234ms
vblank cycle time after write(): 10.0321ms
gamescope: children shut down!
(EE) failed to read Wayland events: Broken pipean:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   RG16 (0x36314752)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
vulkan: Creating Gamescope nested swapchain with format 44 and colorspace 0
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:17] Starting headless backend
wlserver: [xwayland/server.c:108] Starting Xwayland on :0
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x559991e44a10 (res 0x559991ffeae0)
wlserver: [xwayland/server.c:273] Xserver is ready
x86_64 processor:
   Brand: AuthenticAMD
   Model: AMD Ryzen Threadripper PRO 3945WX 12-Cores
   Invariant TSC: True
   cpuid leaf 15H is not supported
   From measurement frequency   3.99 GHz => 250.47 ps
   Sanity check against std::chrono::steady_clock gives frequency   3.99 GHz => 250.47 ps
Measured granularity = 1 tick =>   3.99 GHz, 250.47 ps
nsPerTick: 0.250474
rollingMaxDrawTime: 3000000
rollingMaxDrawTime after using std::clamp: 8333333
offset: 9983333 sleep_cycle: 
vblank cycle time before first sleep: 0.030497ms
rollingMaxDrawTime after using std::clamp: 8333333
offset: 9983333 sleep_cycle: 
vblank cycle time before second wait: 7.80868ms
xwm: execvp failed: No such file or directory
vblank cycle time before write(): 10.0234ms
vblank cycle time after write(): 10.0321ms
gamescope: children shut down!
(EE) failed to read Wayland events: Broken pipe
```

**Comment by tylerfan** [comment]
tried gamescope -w 1920 -h 1080 -r 60 -- vkcube now somehow made it work.

**Comment by sharkautarch** [comment]
> tried gamescope -w 1920 -h 1080 -r 60 -- vkcube now somehow made it work.

The issue you saw in [your first comment](https://github.com/ValveSoftware/gamescope/issues/948#issuecomment-1856352344) was a nvidia driver bug or something 

but I think the issue you saw in [your second comment](https://github.com/ValveSoftware/gamescope/issues/948#issuecomment-1856378111) was actually that you had previously specified `vk-cube` instead of `vkcube` 

See:
> [your comment](https://github.com/ValveSoftware/gamescope/issues/948#issuecomment-1856329428): ... command: ./gamescope vk-cube output:

**Comment by fritz-fritz** [comment]
i believe this may be the same issue that has been plaguing my troubleshooting.

9/10 times gamescope when launched fullscreen with '-f' comes up black but i can tell the game is actually running as inside gamescope if i use obs-gamecapture, I can see the game in obs studio. So it's actually getting rendered but just isn't updating the screen.

i'm using the prepackaged versions of gamescope and nvidia drivers which in my case is 3.12.5-1 and 525.147.05-1. I am running Xorg for my display manager and I have an optimus setup with AMD iGPU and Nvidia dGPU. I also have an external monitor connected as my primary display via HDMI which is tied to the AMDgpu. I use render offloading for my games to utilize the NVIDIA gpu.

When i launch borderless, it seems to display with no problem except my input window is not upscaled until i hit `super+f` meaning i can't click on things in portions of the window until it is fullscreen. ( yeah that part is a different issue)

I don't have much to add other than it sometimes works but mostly not. I would LOVE to get this working so as to leverage FSR upscaling on everything and get better performance out of my old laptop gpu!

**Comment by unhappy-ending** [comment]
> @unhappy-ending are you running embedded ? (If so is that in an X or an Wayland session)

Sorry for the late response. Running nested in Wayland. I've had problems with latest gamescope since, some games refused to launch period and some worked fine no problem. For example, Ducktales Remastered had no problem, but all of the Dark Souls games would CTD. No idea what makes one work vs another. Fell back to gamescope-3.12.5 and had almost no problems other than setting -h and -H to the same resolution. When that happens, the game runs but nothing gets rendered.

Oh, and vsync just doesn't work. Either it renders unsynced, or when I altered dxvk.conf and set a vsync limit it would alternate between 45 to 57 fps, never hitting the 60 target. Kwin would run 60 stable.

>W/ vanilla gamescope, try launching whatever Xwayland app w/: `ENABLE_GAMESCOPE_WSI=0 gamescope ... - <xwayland app>`

@sharkautarch didn't need to with 535.43.20, gamescope worked for the most part. 545 didn't make a difference with or without the env variable, Xwayland always was a black screen.

**Comment by sharkautarch** [comment]
> > @unhappy-ending are you running embedded ? (If so is that in an X or an Wayland session)
> 
> Sorry for the late response. Running nested in Wayland. I've had problems with latest gamescope since, some games refused to launch period and some worked fine no problem. For example, Ducktales Remastered had no problem, but all of the Dark Souls games would CTD. No idea what makes one work vs another. Fell back to gamescope-3.12.5 and had almost no problems other than setting -h and -H to the same resolution. When that happens, the game runs but nothing gets rendered.
> 
> Oh, and vsync just doesn't work. Either it renders unsynced, or when I altered dxvk.conf and set a vsync limit it would alternate between 45 to 57 fps, never hitting the 60 target. Kwin would run 60 stable.
> 
> > W/ vanilla gamescope, try launching whatever Xwayland app w/: `ENABLE_GAMESCOPE_WSI=0 gamescope ... - <xwayland app>`
> 
> @sharkautarch didn't need to with 535.43.20, gamescope worked for the most part. 545 didn't make a difference with or without the env variable, Xwayland always was a black screen.



Hmmm I've been thinking about where your specific issue could be coming from...
Maybe it is an issue w/ nvidia on wlroots...
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3724 

If you were having issues with my `nvidia-fix` branch, I might make a new branch that uses an older version of wlroots...

~~The only other thing I could see is that if the version of xwayland (aka 'xorg-xserver') you have is older than [23.1.2](https://gitlab.freedesktop.org/xorg/xserver/-/commit/79a529dc34ef2fcdf853121004911896e07490fe), then maybe~~ this xwayland issue is also relevant: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1444
EDIT: @unhappy-ending  just realized that xwayland issue is still open (w/ newer comments on it since 1 week ago)
now that I think about it, that xwayland issue seems to fit the problems you were describing...

**Comment by cubanismo** [comment]
For the actual hangs, we fixed them in non-embedded cases and the NV engineer that made that fix tracked down the remaining hang for embedded cases last night to an issue with how Gamescope is creating images (Invalid Vulkan usage that didn't cause any problems until we put in the fix for the other cases). The NVIDIA Developer Vulkan beta drivers should have the fix on the NV side, but we don't recommend those for general use. Upcoming general use drivers will pick up the fix, and @Joshua-Ashton said he'd look into the Gamescope issue.

The various corruption issues aren't related AFAIK, and remain known issues that don't have a resolution yet.

**Comment by weidtn** [comment]
Not sure if that fixed it, but it is working now for me

**Comment by ItzDerock** [comment]
can also confirm that it is working for me now with nvidia 550.67 and gamescope 3.14.2

**Comment by SeongGino** [comment]
Seems to be working now, indeed.

**Comment by nethershaw** [comment]
No. No improvement with nvidia-drivers 560.35.03 and gamescope 3.15.13.

**Comment by cubanismo** [comment]
@nethershaw Can you share details on your system configuration (Ideally run nvidia-bug-report.sh and attach the log it generates), what exactly you're running, and which symptoms exactly you're seeing? We fixed all the hang issues we're aware of, so if you're seeing a hang now, it's likely a separate issue.

**Comment by brain-anti-freeze** [comment]
> @nethershaw Can you share details on your system configuration (Ideally run nvidia-bug-report.sh and attach the log it generates), what exactly you're running, and which symptoms exactly you're seeing? We fixed all the hang issues we're aware of, so if you're seeing a hang now, it's likely a separate issue.

@cubanismo is the issue with using the WSI layer and `vk_present_wait` on Nvidia being tracked ? (I'd call that a hang since the games stop presenting new frames after a short while, even though gamescope continues to function).

**Comment by cubanismo** [comment]
I'm not aware of any outstanding issues with VK_KHR_present_wait other than mixing it with ForceCompositionPipeline or configurations that require that codepath. Can you point me to more details, or file a separate issue if one doesn't exist? While you could call it a hang based on perception, it's clearly not related to the issues tracked & resolved here.

**Comment by matte-schwartz** [comment]
This maybe sounds like what I’ve seen when using Gamescope nested on Plasma Wayland, specifically with the `--hdr-enabled` launch option, on most of the Sony PlayStation 5 PC ports. 

The easiest way to repro would probably be in Ghost of Tsushima, by opening the in-game map and moving the camera around. After around 30-60 seconds, Gamescope appears to “freeze”, but continues playing game audio. Checking Gamescope with `gamescopectl backend_info` doesn’t show any obvious issues, and Gamescope has no indication of anything wrong after shutdown. 

God of War: Ragnarok appears to freeze similarly, although I haven’t found a specific trigger in the game to make it happen consistently. 

I’ll check if there are any matching issues and open a new one if there aren’t, it’s possible it got lost in one of the nvidia megathread type issues

**Comment by Goosegit11** [comment]
happens on 570

**Comment by eNTi** [comment]
```
nvidia-smi 
Thu Jun  5 15:10:47 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.153.02             Driver Version: 570.153.02     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3080 Ti     Off |   00000000:0D:00.0  On |                  N/A |
|  0%   50C    P8             26W /  350W |     220MiB /  12288MiB |     25%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            4272      G   /usr/lib/Xorg                           104MiB |
+-----------------------------------------------------------------------------------------+
```

```
[gamescope] [Info]  console: gamescope version 3.16.9+ (gcc 15.1.1)
[gamescope] [Info]  scriptmgr: Loading scripts from: '/usr/share/gamescope/scripts'
[gamescope] [Info]  scriptmgr: Loading scripts from: '/usr/share/gamescope/scripts/00-gamescope'
[gamescope] [Info]  scriptmgr: Loading scripts from: '/usr/share/gamescope/scripts/00-gamescope/common'
[gamescope] [Info]  scriptmgr: Running script file '/usr/share/gamescope/scripts/00-gamescope/common/inspect.lua' (id: 0)
[gamescope] [Info]  scriptmgr: Running script file '/usr/share/gamescope/scripts/00-gamescope/common/modegen.lua' (id: 1)
[gamescope] [Info]  scriptmgr: Running script file '/usr/share/gamescope/scripts/00-gamescope/common/util.lua' (id: 2)
[gamescope] [Info]  scriptmgr: Loading scripts from: '/usr/share/gamescope/scripts/00-gamescope/displays'
[gamescope] [Info]  scriptmgr: Running script file '/usr/share/gamescope/scripts/00-gamescope/displays/asus.rogally.lcd.lua' (id: 3)
[gamescope] [Info]  scriptmgr: Running script file '/usr/share/gamescope/scripts/00-gamescope/displays/deckhd.steamdeck.deckhd-lcd.lua' (id: 4)
[gamescope] [Info]  scriptmgr: Running script file '/usr/share/gamescope/scripts/00-gamescope/displays/gpd.win4.lcd.lua' (id: 5)
[gamescope] [Info]  scriptmgr: Running script file '/usr/share/gamescope/scripts/00-gamescope/displays/lenovo.legiongo.lcd.lua' (id: 6)
[gamescope] [Info]  scriptmgr: Running script file '/usr/share/gamescope/scripts/00-gamescope/displays/lenovo.legiongos.lcd.lua' (id: 7)
[gamescope] [Info]  scriptmgr: Running script file '/usr/share/gamescope/scripts/00-gamescope/displays/valve.steamdeck.lcd.lua' (id: 8)
[gamescope] [Info]  scriptmgr: Running script file '/usr/share/gamescope/scripts/00-gamescope/displays/valve.steamdeck.oled.lua' (id: 9)
[gamescope] [Info]  scriptmgr: Loading scripts from: '/etc/gamescope/scripts'
[gamescope] [Warn]  scriptmgr: Directory '/etc/gamescope/scripts' does not exist
[gamescope] [Info]  scriptmgr: Loading scripts from: '/home/nt/.config/gamescope/scripts'
[gamescope] [Warn]  scriptmgr: Directory '/home/nt/.config/gamescope/scripts' does not exist
[gamescope] [Info]  vulkan: selecting physical device 'NVIDIA GeForce RTX 3080 Ti': queue family 2 (general queue family 0)
[gamescope] [Info]  vulkan: physical device supports DRM format modifiers
[gamescope] [Error] vulkan: physical device has no render node
terminate called without an active exception
Aborted

```
