### ISSUE TITLE
Gamescope not open in fullscreen Gnome 45

### ISSUE THREAD

**Issue by EliasOfWaffle** [ValveSoftware/gamescope#985]
Gamescope always open in windows mode, the meta + F and the parameter -F or --fullscreen doesn't work.
System: Fedora 39
DE: Gnome 45
Display server: Mutter wayland backend.
Driver: Mesa 23.1.2

**Comment by EliasOfWaffle** [comment]
Resolved, for some reason is working now, WTF????????????????????

**Comment by jarrard** [comment]
Unfortunately I have this issue and it didn't resolve itself.

**Comment by ashleysommer** [comment]
@jarrard  @EliasOfWaffle 

I had this issue on Fedora 38 and Gnome.
I tracked it down to the use of libdecor in newer versions of SDL2 when running on newer versions of Gnome.

I don't know if that should be fixed in SDL2, or in libdecor, but in any case, I can work around it in Gamescope with the very helpful libdecor killswitch:
`env SDL_VIDEO_WAYLAND_PREFER_LIBDECOR=0 gamescope -f -- glxgears`.
Now it works exactly as expected, and same as it does on KDE Plasma.

**Comment by MarbleXeno** [comment]
@ashleysommer unfortunately setting that environment variable does not work for me. I have the same exact problem on Gnome 45 (Wayland).

Launching a fullscreen instance of gamescope works only on secondary display, while setting the gamescope's output display through -O it launches on the main one but with libdecor window decorations visible and not fullscreened.

I found the solution though, in Gnome Settings you can go to Keyboard section and add a custom shortcut called "Toggle fullscreen mode". This forces window to go fullscreen, eliminating visible libdecor decorations.

**Comment by DeedleFake** [comment]
Another possible solution: Run gamescope with `SDL_VIDEODRIVER=x11`. That fixed every single weird gamescope bug I'd been having.

**Comment by Aarontheissueguy** [comment]
The easiest solution I found was setting a keyboard shortcut to toggle fullscreen in the gnome settings. You can just toggle it than

**Comment by darkbasic** [comment]
For me `-f` works randomly on Gnome: sometimes it prints decorations, sometimes it doesn't.

**Comment by Saroumane** [comment]
Hello, can someone tell me if this is still reproduced with Gnome and gamescope 3.14.3 please ?
I do reproduce it with gamescope 3.14.2 and can't upgrade to 3.14.3 because it crash at startup for any X11 app ( https://github.com/ValveSoftware/gamescope/issues/1249 )

**Comment by darkbasic** [comment]
I'm not sure but Gnome 46 is f***ed as hell: it recently started opening the Steam client in fullscreen mode on my external monitor, but not on my laptop's monitor.

**Comment by Saroumane** [comment]
Yes, multi-monitor with Linux has always been difficult to use. 
Finally I installed the latest gamescope-git version ( `3.14.13.r0.gd404e0f-1` ) : I do reproduce this bug (and --reshade-effect flag seems broken).
So maybe this bug should be re-opened ?

Besides workarounds like `SDL_VIDEO_WAYLAND_PREFER_LIBDECOR=0` and `SDL_VIDEODRIVER=x11` do not work on my system (Archlinux + Gnome)

**Comment by DistantThunder** [comment]
This is a problem under KDE as well, when running gamescope in a Steam game it can't get fullscreen when the actual application launches until I specifically press "Super + F". This behavior doesn't manifest outside of Steam.

The `SDL_VIDEO_WAYLAND_PREFER_LIBDECOR=0` however works for me right now on Arch + Plasma + Mesa AMD. Keypresses aren't ideal for couch gaming (or streaming through Moonlight).

**Comment by DeedleFake** [comment]
Another workaround: `env -u WAYLAND_DISPLAY gamescope ...`

From what I know, gamescope had some changes to how it handles window creation and it no longer necessarily uses SDL. Using the above will force it to use Xwayland regardless of whether it's using SDL or not, although I will note that, while it still has some problems, the new, non-SDL backend seems better than the SDL one.
